### ISSUE TITLE
i try to use feed_dict method to test my work,but optimizer has error

### ISSUE THREAD

**Issue by GuanlinLee** [jwohlwend/CNNEncrypt#1]
ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients, between variables.could you tell me what happens plz

**Comment by jwohlwend** [comment]
Hi, sorry for the late reply. Quick disclaimer I'm not a tensorflow expert by any means, but I'm happy to try to help. How are you creating the data to be fed? As you can see in my code, I do not use the feed_dict method as my data is created using Tensorflow methods. If you are trying to feed it, you may want to create the data outside of the graph using numpy for instance. Hope this helps..

**Comment by GuanlinLee** [comment]
thx,i have already made it.
